namespace DotNetPaymentSDK.Config.Enums
{
    public static class CurrencyCodes
    {
        public const string AED = "AED"; // United Arab Emirates Dirham
        public const string AFN = "AFN"; // Afghan Afghani
        public const string ALL = "ALL"; // Albanian Lek
        public const string AMD = "AMD"; // Armenian Dram
        public const string ANG = "ANG"; // Netherlands Antillean Guilder
        public const string AOA = "AOA"; // Angolan Kwanza
        public const string ARS = "ARS"; // Argentine Peso
        public const string AUD = "AUD"; // Australian Dollar
        public const string AWG = "AWG"; // Aruban Florin
        public const string AZN = "AZN"; // Azerbaijani Manat
        public const string BAM = "BAM"; // Bosnia-Herzegovina Convertible Mark
        public const string BBD = "BBD"; // Barbadian Dollar
        public const string BDT = "BDT"; // Bangladeshi Taka
        public const string BGN = "BGN"; // Bulgarian Lev
        public const string BHD = "BHD"; // Bahraini Dinar
        public const string BIF = "BIF"; // Burundian Franc
        public const string BMD = "BMD"; // Bermudan Dollar
        public const string BND = "BND"; // Brunei Dollar
        public const string BOB = "BOB"; // Bolivian Boliviano
        public const string BRL = "BRL"; // Brazilian Real
        public const string BSD = "BSD"; // Bahamian Dollar
        public const string BTC = "BTC"; // Bitcoin
        public const string BTN = "BTN"; // Bhutanese Ngultrum
        public const string BWP = "BWP"; // Botswanan Pula
        public const string BYN = "BYN"; // Belarusian Ruble
        public const string BZD = "BZD"; // Belize Dollar
        public const string CAD = "CAD"; // Canadian Dollar
        public const string CDF = "CDF"; // Congolese Franc
        public const string CHF = "CHF"; // Swiss Franc
        public const string CLF = "CLF"; // Chilean Unit of Account (UF)
        public const string CLP = "CLP"; // Chilean Peso
        public const string CNH = "CNH"; // Chinese Yuan (Offshore)
        public const string CNY = "CNY"; // Chinese Yuan
        public const string COP = "COP"; // Colombian Peso
        public const string CRC = "CRC"; // Costa Rican Colón
        public const string CUC = "CUC"; // Cuban Convertible Peso
        public const string CUP = "CUP"; // Cuban Peso
        public const string CVE = "CVE"; // Cape Verdean Escudo
        public const string CZK = "CZK"; // Czech Republic Koruna
        public const string DJF = "DJF"; // Djiboutian Franc
        public const string DKK = "DKK"; // Danish Krone
        public const string DOP = "DOP"; // Dominican Peso
        public const string DZD = "DZD"; // Algerian Dinar
        public const string EGP = "EGP"; // Egyptian Pound
        public const string ERN = "ERN"; // Eritrean Nakfa
        public const string ETB = "ETB"; // Ethiopian Birr
        public const string EUR = "EUR"; // Euro
        public const string FJD = "FJD"; // Fijian Dollar
        public const string FKP = "FKP"; // Falkland Islands Pound
        public const string GBP = "GBP"; // British Pound Sterling
        public const string GEL = "GEL"; // Georgian Lari
        public const string GGP = "GGP"; // Guernsey Pound
        public const string GHS = "GHS"; // Ghanaian Cedi
        public const string GIP = "GIP"; // Gibraltar Pound
        public const string GMD = "GMD"; // Gambian Dalasi
        public const string GNF = "GNF"; // Guinean Franc
        public const string GTQ = "GTQ"; // Guatemalan Quetzal
        public const string GYD = "GYD"; // Guyanaese Dollar
        public const string HKD = "HKD"; // Hong Kong Dollar
        public const string HNL = "HNL"; // Honduran Lempira
        public const string HRK = "HRK"; // Croatian Kuna
        public const string HTG = "HTG"; // Haitian Gourde
        public const string HUF = "HUF"; // Hungarian Forint
        public const string IDR = "IDR"; // Indonesian Rupiah
        public const string ILS = "ILS"; // Israeli New Sheqel
        public const string IMP = "IMP"; // Manx pound
        public const string INR = "INR"; // Indian Rupee
        public const string IQD = "IQD"; // Iraqi Dinar
        public const string IRR = "IRR"; // Iranian Rial
        public const string ISK = "ISK"; // Icelandic Króna
        public const string JEP = "JEP"; // Jersey Pound
        public const string JMD = "JMD"; // Jamaican Dollar
        public const string JOD = "JOD"; // Jordanian Dinar
        public const string JPY = "JPY"; // Japanese Yen
        public const string KES = "KES"; // Kenyan Shilling
        public const string KGS = "KGS"; // Kyrgystani Som
        public const string KHR = "KHR"; // Cambodian Riel
        public const string KMF = "KMF"; // Comorian Franc
        public const string KPW = "KPW"; // North Korean Won
        public const string KRW = "KRW"; // South Korean Won
        public const string KWD = "KWD"; // Kuwaiti Dinar
        public const string KYD = "KYD"; // Cayman Islands Dollar
        public const string KZT = "KZT"; // Kazakhstani Tenge
        public const string LAK = "LAK"; // Laotian Kip
        public const string LBP = "LBP"; // Lebanese Pound
        public const string LKR = "LKR"; // Sri Lankan Rupee
        public const string LRD = "LRD"; // Liberian Dollar
        public const string LSL = "LSL"; // Lesotho Loti
        public const string LYD = "LYD"; // Libyan Dinar
        public const string MAD = "MAD"; // Moroccan Dirham
        public const string MDL = "MDL"; // Moldovan Leu
        public const string MGA = "MGA"; // Malagasy Ariary
        public const string MKD = "MKD"; // Macedonian Denar
        public const string MMK = "MMK"; // Myanmar Kyat
        public const string MNT = "MNT"; // Mongolian Tugrik
        public const string MOP = "MOP"; // Macanese Pataca
        public const string MRO = "MRO"; // Mauritanian Ouguiya (pre-2018)
        public const string MRU = "MRU"; // Mauritanian Ouguiya
        public const string MUR = "MUR"; // Mauritian Rupee
        public const string MVR = "MVR"; // Maldivian Rufiyaa
        public const string MWK = "MWK"; // Malawian Kwacha
        public const string MXN = "MXN"; // Mexican Peso
        public const string MYR = "MYR"; // Malaysian Ringgit
        public const string MZN = "MZN"; // Mozambican Metical
        public const string NAD = "NAD"; // Namibian Dollar
        public const string NGN = "NGN"; // Nigerian Naira
        public const string NIO = "NIO"; // Nicaraguan Córdoba
        public const string NOK = "NOK"; // Norwegian Krone
        public const string NPR = "NPR"; // Nepalese Rupee
        public const string NZD = "NZD"; // New Zealand Dollar
        public const string OMR = "OMR"; // Omani Rial
        public const string PAB = "PAB"; // Panamanian Balboa
        public const string PEN = "PEN"; // Peruvian Sol
        public const string PGK = "PGK"; // Papua New Guinean Kina
        public const string PHP = "PHP"; // Philippine Peso
        public const string PKR = "PKR"; // Pakistani Rupee
        public const string PLN = "PLN"; // Polish Zloty
        public const string PYG = "PYG"; // Paraguayan Guarani
        public const string QAR = "QAR"; // Qatari Rial
        public const string RON = "RON"; // Romanian Leu
        public const string RSD = "RSD"; // Serbian Dinar
        public const string RUB = "RUB"; // Russian Ruble
        public const string RWF = "RWF"; // Rwandan Franc
        public const string SAR = "SAR"; // Saudi Riyal
        public const string SBD = "SBD"; // Solomon Islands Dollar
        public const string SCR = "SCR"; // Seychellois Rupee
        public const string SDG = "SDG"; // Sudanese Pound
        public const string SEK = "SEK"; // Swedish Krona
        public const string SGD = "SGD"; // Singapore Dollar
        public const string SHP = "SHP"; // Saint Helena Pound
        public const string SLL = "SLL"; // Sierra Leonean Leone
        public const string SOS = "SOS"; // Somali Shilling
        public const string SRD = "SRD"; // Surinamese Dollar
        public const string SSP = "SSP"; // South Sudanese Pound
        public const string STD = "STD"; // São Tomé and Príncipe Dobra (pre-2018)
        public const string STN = "STN"; // São Tomé and Príncipe Dobra
        public const string SVC = "SVC"; // Salvadoran Colón
        public const string SYP = "SYP"; // Syrian Pound
        public const string SZL = "SZL"; // Swazi Lilangeni
        public const string THB = "THB"; // Thai Baht
        public const string TJS = "TJS"; // Tajikistani Somoni
        public const string TMT = "TMT"; // Turkmenistani Manat
        public const string TND = "TND"; // Tunisian Dinar
        public const string TOP = "TOP"; // Tongan Pa'anga
        public const string TRY = "TRY"; // Turkish Lira
        public const string TTD = "TTD"; // Trinidad and Tobago Dollar
        public const string TWD = "TWD"; // New Taiwan Dollar
        public const string TZS = "TZS"; // Tanzanian Shilling
        public const string UAH = "UAH"; // Ukrainian Hryvnia
        public const string UGX = "UGX"; // Ugandan Shilling
        public const string USD = "USD"; // United States Dollar
        public const string UYU = "UYU"; // Uruguayan Peso
        public const string UZS = "UZS"; // Uzbekistan Som
        public const string VEF = "VEF"; // Venezuelan Bolívar Fuerte (Old)
        public const string VES = "VES"; // Venezuelan Bolívar Soberano
        public const string VND = "VND"; // Vietnamese Dong
        public const string VUV = "VUV"; // Vanuatu Vatu
        public const string WST = "WST"; // Samoan Tala
        public const string XAF = "XAF"; // CFA Franc BEAC
        public const string XAG = "XAG"; // Silver Ounce
        public const string XAU = "XAU"; // Gold Ounce
        public const string XCD = "XCD"; // East Caribbean Dollar
        public const string XDR = "XDR"; // Special Drawing Rights
        public const string XOF = "XOF"; // CFA Franc BCEAO
        public const string XPD = "XPD"; // Palladium Ounce
        public const string XPF = "XPF"; // CFP Franc
        public const string XPT = "XPT"; // Platinum Ounce
        public const string YER = "YER"; // Yemeni Rial
        public const string ZAR = "ZAR"; // South African Rand
        public const string ZMW = "ZMW"; // Zambian Kwacha (pre-2013)
        public const string ZWL = "ZWL"; // Zimbabwean Dollar

        public static bool IsValid(string currencyCode)
        {
            return typeof(CurrencyCodes).GetField(currencyCode)?.GetValue(null) != null;
        }
    }
}
